### ISSUE TITLE
Duplicate Code

### ISSUE THREAD

**Issue by pavlospt** [RobbeSneyders/Modular2Recycler#1]
Hello, nice library and thank you for Open Sourcing it. 

The following lines are duplicated because of some reason or just by mistake https://github.com/RobbeSneyders/UndoRecycler/blob/master/library/src/main/java/com/cuttingedge/undorecycler/UndoAdapter.java#L246 ?

**Comment by RobbeSneyders** [comment]
Thanks for reviewing the code.

This is to remove both the header (if needed) and the item.
I'll replace it with the following, which is shorter and more intuitive:

```
list.remove(position);
list.remove(position - 1);
notifyItemRangeRemoved(position -1, 2);
```
