### ISSUE TITLE
Add a sample module for this library

### ISSUE THREAD

**Issue by cesarferreira** [RobbeSneyders/Modular2Recycler#2]
To increase the library engage you should add a sample usage module to your project

> gem install dryrun
> dryrun https://github.com/RobbeSneyders/UndoRecycler

I was trying to run this and it didn't work, I was surprised to see that you had no sample since you have a beautiful gif of a "sample" :)

**Comment by RobbeSneyders** [comment]
The gif is part of a [more extensive app](https://play.google.com/store/apps/details?id=com.cuttingedge.swipeshortcuts). However that app seemed a bit too complicated to put up as an example for the library and it doesn't ship with a filled database. I will build a barebone example in a few days. For now, the readme has a "How to use" example.

Thanks for the feedback!

**Comment by RobbeSneyders** [comment]
The example app is now added to the project. I will add gifs of the new app soon.

**Comment by cesarferreira** [comment]
That's one cool ass Demo app man 👍 great job
