### ISSUE TITLE
Separate extensions from this library

### ISSUE THREAD

**Issue by saket** [RobbeSneyders/Modular2Recycler#4]
Hello, I just stumbled across your library and the design pattern looks pretty solid. But I'm slightly sad because it's trying to solve multiple problems by including extensions such as drag-and-drop, etc. I think this is bad because the extensions are not the job of `Modular2Recycler` as well as because I'm restricted to using only those extensions. I'd strongly recommend splitting this library.

**Comment by RobbeSneyders** [comment]
Hello and thanks for the feedback.

I want to start by pointing out that you can use this library without using the plugins. You can also add your own plugins by extending the ModularAdapter class.

That being said, I do agree that it's a good idea to split the functionality, or at least extract a second library without the plugins. I'll look into this in a couple of days.

**Comment by RobbeSneyders** [comment]
I currently don't have the time to work on this. I will look into this later. In the mean time, all contributions are appreciated.
