### ISSUE TITLE
AdapterModule passing `this` out of constructor, potential leak

### ISSUE THREAD

**Issue by Net-Geek** [RobbeSneyders/Modular2Recycler#5]
The AdapterModule class passes a reference to `this` to an external class in its constructor. Seems like this could potentially create a leak, no?

**Comment by RobbeSneyders** [comment]
You're right, it's bad practice. Thank you for pointing this out.

I'll remove it and let the user add the module himself like this:
`adapter.addModule(new AdapterModule())`

**Comment by Net-Geek** [comment]
Cool. Regardless, really dig the composition of the library. Great work.

**Comment by Net-Geek** [comment]
Better yet, heres _probably_ the best solution: [#6](https://github.com/RobbeSneyders/Modular2Recycler/pull/6). This ensures the module has been fully constructed but also doesn't force the activity to add the module directly which causes unchecked method invocation warnings at the activity level.

**Comment by RobbeSneyders** [comment]
Thanks! Issue has been fixed by merge e3fab2f.
