### ISSUE TITLE
Allow us to set the items in order to use DiffUtils

### ISSUE THREAD

**Issue by TammiLion** [RobbeSneyders/Modular2Recycler#7]
Documentation from dispatchUpdatesTo: 

```List oldList = mAdapter.getData();
DiffResult result = DiffUtil.calculateDiff(new MyCallback(oldList, newList));
mAdapter.setData(newList);
result.dispatchUpdatesTo(mAdapter);```

**Comment by RobbeSneyders** [comment]
I'm not familiar with DiffUtils, but if I understand correctly, you need [this method](https://github.com/RobbeSneyders/Modular2Recycler/blob/master/library/src/main/java/com/cuttingedge/adapter2recycler/Adapter/ModularAdapter.java#L108) without the `notifyDataSetChanged()` call?

**Comment by TammiLion** [comment]
Yes that would be great. If you'd like to know more:

https://medium.com/@nullthemall/diffutil-is-a-must-797502bc1149#.1f4l2mk2f

**Comment by RobbeSneyders** [comment]
I added [this method](https://github.com/RobbeSneyders/Modular2Recycler/blob/master/library/src/main/java/com/cuttingedge/adapter2recycler/Adapter/ModularAdapter.java#L120):  
`public void swap(List<I> newList, boolean notify)`

So now you can use it like this:
```
mAdapter.swap(newList, false)
result.dispatchUpdatesTo(mAdapter)
```

[I also added DiffUtil in the sample app](https://github.com/RobbeSneyders/Modular2Recycler/blob/master/app/src/main/java/com/cuttingedge/PokeApp/Backpack/BackpackActivity.java#L93)

I hope this works for you. Thanks for the feedback!
