### ISSUE TITLE
Back navigation after orientation change bug

### ISSUE THREAD

**Issue by TammiLion** [RobbeSneyders/Modular2Recycler#8]
Hey,

Here are the steps to reproduce not seeing a list of items:

- Show a list of items like you would normally
- Change to portrait/ landscape (list will still be shown)
- Navigate to other activity
- Go back to previous activity (list is now gone)

Unfortunately I have no idea what goes wrong. I rewrote the code to use a normal adapter and now it works but I was hoping to use yours :)

**Comment by RobbeSneyders** [comment]
Is this a bug in your own app or in the sample app provided with the library?

I can't reproduce it with the sample app.

**Comment by TammiLion** [comment]
If you can't reproduce it with the sample app then the bug is in my code. My apologies.

**Comment by RobbeSneyders** [comment]
No problem. You can compare your code with the [source code of the sample app](https://github.com/RobbeSneyders/Modular2Recycler/blob/master/app) to find your problem. You can also [download it from the Play Store](https://play.google.com/store/apps/details?id=com.cuttingedge.pokeapp) to check if you can reproduce the bug.
